import Navigation from "../components/navigation/Navigation"
import "./../styles/global.css"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <Navigation />

        {children}
      </body>
    </html>
  )
}
